version: '3'
services:
  backend:
    volumes:
      - ./backend:/app
    command: >
      /bin/sh -c "python manage.py makemigrations users &&
                  python manage.py migrate &&
                  pytest users/tests/* &&
                  python manage.py runserver 0.0.0.0:8000"
  frontend:
    volumes:
      - ./frontend:/app
